#!/usr/bin/env python3
"""Regenerate or verify the embedded thin-client HTML header."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "package" / "nes-emulator" / "src" / "play.html"
HEADER = ROOT / "package" / "nes-emulator" / "src" / "play.html.h"


def render(source: str) -> str:
    lines = [
        "/* Generated by scripts/embed-play-html.py; edit play.html, not this file. */",
        "#ifndef PLAY_HTML_H",
        "#define PLAY_HTML_H",
        "",
        "static const char PLAY_HTML[] =",
    ]
    for line in source.splitlines(keepends=True):
        lines.append(json.dumps(line, ensure_ascii=False))
    if source and not source.endswith(("\n", "\r")):
        pass
    lines.extend([";", "", "#endif", ""])
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail instead of updating when play.html.h is stale",
    )
    args = parser.parse_args()

    expected = render(SOURCE.read_text(encoding="utf-8"))
    current = HEADER.read_text(encoding="utf-8") if HEADER.exists() else ""
    if current == expected:
        return 0
    if args.check:
        print(f"{HEADER.relative_to(ROOT)} is stale", file=sys.stderr)
        return 1
    HEADER.write_text(expected, encoding="utf-8", newline="\n")
    print(f"updated {HEADER.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
